description:  ${spring.application.description}
title:  ${spring.application.name}
version:  ${spring.application.version}

info:
  app:
    id: ${spring.application.id}
    name: ${spring.application.name}
    version: ${spring.application.version}

servlet:
  port: 14002

spring:
  application:
    description: Lostboyz queue service
    id: lostboyz-queue-service
    name: lostboyz-queue-service
    version: 0.0.1-SNAPSHOT
  output:
    ansi:
      enabled: detect